name: foodly_restaurant
#dbestech property. visit www.dbestech.com
description: A new Flutter project.

publish_to: none

version: 3.3.5+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.9.0
  flutter_polyline_points: ^2.0.0
  geolocator: ^14.0.0
  geocoding: ^2.0.0
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  get: ^4.6.6
  flutter_vector_icons: ^2.0.0
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  flutter_hooks: ^0.20.3
  cloud_firestore:
  http: ^1.1.0
  shimmer: ^3.0.0
  glass: ^1.0.2+1
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  get_storage: ^2.1.1
  image_picker: ^1.0.4
  firebase_storage: ^12.4.5
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  device_preview: ^1.1.0
  otp_text_field: ^1.1.3
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.0.0
  firebase_messaging: ^15.2.5
  pull_to_refresh: ^2.0.0
  location: ^7.0.0
  syncfusion_flutter_charts: ^29.1.39
  photo_view:
  package_info_plus: ^8.3.0
  dio: ^5.5.0+1
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  flutter_easyloading: ^3.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/anime/
    - assets/icons/
    - .env.development
    - .env.production